In [1]:
# !pip install datasets==2.18.0

In [2]:
# !pip install ragas==0.1.9

## 分步

In [5]:
from dotenv import load_dotenv

# 加载环境变量
load_dotenv()

True

In [6]:
# 创建数据样本
data_samples = {
    'question': ['第一次超级碗是什么时候？', '谁赢得了最多的超级碗？'],
    'answer': ['第一次超级碗是在1967年1月15日举行的', '赢得最多超级碗的是新英格兰爱国者队'],
    'contexts' : [['第一次AFL-NFL世界冠军赛是一场于1967年1月15日在洛杉矶纪念体育场举行的美式足球比赛，'], 
    ['绿湾包装工队...威斯康星州绿湾市。', '包装工队竞争...足球会议']],
    'ground_truth': ['第一次超级碗是在1967年1月15日举行的', '新英格兰爱国者队已经赢得了创纪录的六次超级碗']
}

In [7]:
from datasets import Dataset

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)

In [8]:
# 查看数据集的信息，输出将显示数据集的特征和行数
dataset

Dataset({
    features: ['question', 'answer', 'contexts', 'ground_truth'],
    num_rows: 2
})

In [9]:
type(dataset)

datasets.arrow_dataset.Dataset

In [10]:
from ragas import evaluate
from ragas.metrics import faithfulness, answer_correctness

# 使用evaluate函数评估dataset，采用faithfulness和answer_correctness作为度量标准
score = evaluate(dataset, metrics=[faithfulness, answer_correctness])

Evaluating:   0%|          | 0/4 [00:00<?, ?it/s]

In [11]:
score

{'faithfulness': 0.5000, 'answer_correctness': 0.8031}

In [12]:
type(score)

ragas.evaluation.Result

In [13]:
# 将评估结果转换为Pandas DataFrame格式
score.to_pandas()

,question,answer,contexts,ground_truth,faithfulness,answer_correctness
0,第一次超级碗是什么时候？,第一次超级碗是在1967年1月15日举行的,[第一次AFL-NFL世界冠军赛是一场于1967年1月15日在洛杉矶纪念体育场举行的美式足球...,第一次超级碗是在1967年1月15日举行的,1.0,1.000000
1,谁赢得了最多的超级碗？,赢得最多超级碗的是新英格兰爱国者队,"[绿湾包装工队...威斯康星州绿湾市。, 包装工队竞争...足球会议]",新英格兰爱国者队已经赢得了创纪录的六次超级碗,0.0,0.606142

## 整体

In [3]:
from dotenv import load_dotenv
from datasets import Dataset 
import os
from ragas import evaluate
from ragas.metrics import faithfulness, answer_correctness


# 加载环境变量
load_dotenv()

# 创建数据样本
data_samples = {
    'question': ['第一次超级碗是什么时候？', '谁赢得了最多的超级碗？'],
    'answer': ['第一次超级碗是在1967年1月15日举行的', '赢得最多超级碗的是新英格兰爱国者队'],
    'contexts' : [['第一次AFL-NFL世界冠军赛是一场于1967年1月15日在洛杉矶纪念体育场举行的美式足球比赛，'], 
    ['绿湾包装工队...威斯康星州绿湾市。', '包装工队竞争...足球会议']],
    'ground_truth': ['第一次超级碗是在1967年1月15日举行的', '新英格兰爱国者队已经赢得了创纪录的六次超级碗']
}

# 从字典中创建Dataset对象
dataset = Dataset.from_dict(data_samples)

# 使用evaluate函数评估dataset，采用faithfulness和answer_correctness作为度量标准
score = evaluate(dataset, metrics=[faithfulness,answer_correctness])

# 将评估结果转换为Pandas DataFrame格式
score.to_pandas()

Evaluating:   0%|          | 0/4 [00:00<?, ?it/s]

,question,answer,contexts,ground_truth,faithfulness,answer_correctness
0,第一次超级碗是什么时候？,第一次超级碗是在1967年1月15日举行的,[第一次AFL-NFL世界冠军赛是一场于1967年1月15日在洛杉矶纪念体育场举行的美式足球...,第一次超级碗是在1967年1月15日举行的,1.0,1.000000
1,谁赢得了最多的超级碗？,赢得最多超级碗的是新英格兰爱国者队,"[绿湾包装工队...威斯康星州绿湾市。, 包装工队竞争...足球会议]",新英格兰爱国者队已经赢得了创纪录的六次超级碗,0.0,0.231142

In [4]:
score

{'faithfulness': 0.5000, 'answer_correctness': 0.6156}